// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    return $('.dot').on('click', function(event) {
      var that;
      that = $(this);
      return Thinker.clickedEvent(that);
    });
  });

}).call(this);

//# sourceMappingURL=document.js.map
