// Generated by CoffeeScript 1.10.0
(function() {
  var superClick;

  $(function() {
    var timeoutID;
    timeoutID = 0;
    $('.dot').on('mousedown', function() {
      window.running = true;
      return timeoutID = setTimeout(superClick, 1000);
    });
    $('.dot').on('mouseup', function() {
      var that;
      clearTimeout(timeoutID);
      that = $(this);
      if (window.running) {
        Thinker.iconClicked(that);
      }
      return window.running = false;
    });
    return $('.dot').on('mouseout', function() {
      return clearTimeout(timeoutID);
    });
  });

  superClick = function() {
    return alert('super!');
  };

}).call(this);

//# sourceMappingURL=document.js.map
